codecov:
  notify:
    after_n_builds: 1

coverage:
  status:
    project: off
    patch: off
    changes:
      default:
        target: 80%
        if_not_found: success

ignore:
  - "packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests"
