"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DART_RESERVED_KEYWORDS = exports.typeToEnumMap = exports.IGNORE_FOR_FILE = exports.COLLECTION_PACKAGE = exports.BASE_IMPORT_PACKAGES = exports.LOADER_CLASS_NAME = void 0;
exports.LOADER_CLASS_NAME = 'ModelProvider';
exports.BASE_IMPORT_PACKAGES = [
    'package:flutter/foundation.dart',
    'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart'
];
exports.COLLECTION_PACKAGE = 'package:collection/collection.dart';
exports.IGNORE_FOR_FILE = '// ignore_for_file: public_member_api_docs';
exports.typeToEnumMap = {
    String: '.string',
    Int: '.int',
    Float: '.double',
    Boolean: '.bool',
    AWSDate: '.date',
    AWSDateTime: '.dateTime',
    AWSTime: '.time',
    AWSTimestamp: '.timestamp',
    AWSEmail: '.string',
    AWSJSON: '.string',
    AWSURL: '.string',
    AWSPhone: '.string',
    AWSIPAddress: '.string',
};
exports.DART_RESERVED_KEYWORDS = [
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'Function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'library',
    'mixin',
    'new',
    'null',
    'on',
    'operator',
    'part',
    'rethrow',
    'return',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'typedef',
    'var',
    'void',
    'while',
    'with',
    'yield'
];
//# sourceMappingURL=dart-config.js.map