export const LOADER_CLASS_NAME = 'ModelProvider';
export const BASE_IMPORT_PACKAGES = ['package:flutter/foundation.dart', 'package:amplify_core/amplify_core.dart'];
export const COLLECTION_PACKAGE = 'package:collection/collection.dart';

export const IGNORE_FOR_FILE = '// ignore_for_file: public_member_api_docs';

export const typeToEnumMap: Record<string, string> = {
  String: '.string',
  Int: '.int',
  Float: '.double',
  Boolean: '.bool',
  AWSDate: '.date',
  AWSDateTime: '.dateTime',
  AWSTime: '.time',
  AWSTimestamp: '.timestamp',
  AWSEmail: '.string',
  AWSJSON: '.string',
  AWSURL: '.string',
  AWSPhone: '.string',
  AWSIPAddress: '.string',
};

export const DART_RESERVED_KEYWORDS = [
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'Function',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'rethrow',
  'return',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'while',
  'with',
  'yield',
];
