version: 2.1
machine:
  environment:
    PATH: '${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin'
executors:
  linux-node10:
    docker:
      - image: circleci/node:10.0
    resource_class: large
  linux-node15:
    docker:
      - image: circleci/node:15.0
    resource_class: large

defaults: &defaults
  working_directory: ~/repo
  parameters:
      os:
        type: executor

install_cli_with_local_codegen: &install_cli
  name: install Amplify CLI and amplify-app with local Amplify Codegen
  command: |
    npm get prefix
    echo $OLD_CLI_BINARY
    source .circleci/local_publish_helpers.sh
    local_registry=http://localhost:4873
    startLocalRegistry "$(pwd)/.circleci/verdaccio.yaml"
    setNpmRegistryUrlToLocal "$local_registry"
    git config user.email not@used.com
    git config user.name "Doesnt Matter"
    yarn verdaccio-publish || yarn verdaccio-publish
    sudo npm install -g @aws-amplify/cli --registry $local_registry
    sudo npm install -g amplify-app --registry $local_registry
    amplify -v
    amplify-app --version
    unsetNpmRegistryUrl
  working_directory: ~/repo
        
clean_up_e2e_resources: &cleanup_e2e
  name: Clean up e2e resources
  command: |
    pwd
    cd packages/amplify-codegen-e2e-tests
    yarn clean-e2e-resources job ${CIRCLE_BUILD_NUM}
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    executor: << parameters.os >>
    steps:
      - checkout
      - run: yarn config set workspaces-experimental true
      - run: yarn cache clean --force
      - run: yarn run production-build
      - save_cache:
          key: amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - save_cache:
          key: amplify-codegen-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test-ci
      - run:
          name: Collect code coverage
          command: yarn coverage

  deploy:
    <<: *defaults
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - amplify-codegen-ssh-deps-{{ .Branch }}
            - amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish Amplify Codegen
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              git config --global user.email $GITHUB_EMAIL
              git config --global user.name $GITHUB_USER
              npm run publish:$CIRCLE_BRANCH
            else
              echo "Skipping deploy."
            fi

  e2e-test:
    <<: *defaults
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: 
          name: Install old CLI in separate local folder
          command: |
            source .circleci/local_publish_helpers.sh
            npmGlobalPath = $(npm get prefix)
            echo $npmGlobalPath
            changeNpmGlobalPath "~/.my-npm-global"
            sudo npm i -g @aws-amplify/cli@4.40.0
            export OLD_CLI_BINARY = "~/.my-npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify"
            changeNpmGlobalPath "$npmGlobalPath"
      - run: *install_cli
      - run:
          name: Run e2e tests
          command: |
            cd packages/amplify-codegen-e2e-tests
            yarn run e2e --maxWorkers=3
      - store_test_results:
          path: packages/amplify-codegen-e2e-tests/
      - store_artifacts:
          path: ~/repo/packages/amplify-codegen-e2e-tests/amplify-e2e-reports

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          name: build-<< matrix.os >>
          matrix:
            parameters:
              os: [linux-node15, linux-node10]
      - test:
          name: test-<< matrix.os >>
          matrix:
            parameters:
              os: [linux-node15, linux-node10]
          requires:
            - build-<< matrix.os >>
      - e2e-test:
          name: e2e-test-<< matrix.os >>
          matrix:
            parameters:
              os: [linux-node15, linux-node10]
          requires:
            - build-<< matrix.os >>
            - test-<< matrix.os >>
          filters:
            branches:
              only:
                - e2e-testing
      - deploy:
          os: linux-node15
          requires:
            - build
            - test
            - e2e-test
          filters:
            branches:
              only:
                - release
                - master