# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'EndToEndSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'

  target 'EndToEndSampleTests' do
    inherit! :search_paths
  end

end
